/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as
published by the Free Software Foundation, either version 3 of the
License, or (at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU Affero General Public License for more details.

You should have received a copy of the GNU Affero General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

For commercial licensing, please contact support@quantumnous.com
*/
import { useQuery } from '@tanstack/react-query'
import type { ReactNode } from 'react'
import { useTranslation } from 'react-i18next'

import { RichContent } from '@/components/rich-content'
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from '@/components/ui/alert-dialog'
import { Button } from '@/components/ui/button'
import { Skeleton } from '@/components/ui/skeleton'
import { getUserAgreement } from '@/features/legal/api'
import { isHttpUrl, isLikelyHtml } from '@/lib/content-format'

type UsageStatementDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  onAgree: () => void
}

export function UsageStatementDialog(props: UsageStatementDialogProps) {
  const { t } = useTranslation()
  const { data, isLoading } = useQuery({
    queryKey: ['user-agreement'],
    queryFn: getUserAgreement,
    enabled: props.open,
    staleTime: 10 * 60 * 1000,
  })

  const rawContent = data?.data?.trim() ?? ''
  const hasConfiguredContent = (data?.success ?? false) && rawContent.length > 0
  const isExternalLink = hasConfiguredContent && isHttpUrl(rawContent)
  const contentIsHtml = hasConfiguredContent && isLikelyHtml(rawContent)

  const defaultStatementItems = [
    t(
      'This site is an AI API relay service. It only forwards requests to upstream model providers; model outputs are generated by upstream services and do not represent the position of this site.'
    ),
    t(
      'Data generated or submitted while using this service (including but not limited to request content, generated results, and usage records) may be used by this site to the extent permitted by law and necessary for providing the service, improving the service, and safeguarding the platform.'
    ),
    t(
      'You must not use this service to generate or distribute content that violates applicable laws and regulations, infringes the rights of others, or harms this site or third parties. Violating accounts may be suspended or terminated.'
    ),
    t(
      'For accounts suspected of violating this statement, abusing the service (including but not limited to account sharing, malicious request flooding, bypassing restrictions, or unauthorized resale of the API), or posing security risks, this site may apply rate limiting, suspension, or bans as appropriate, and may withhold refunds of the related balance.'
    ),
    t(
      'Keep your account credentials and API keys safe. Consumption caused by leaked keys is charged to your account.'
    ),
    t(
      'Usage is billed based on actual consumption. Top-ups and consumed quota are generally non-refundable unless otherwise required by law or promised by this site.'
    ),
    t(
      'This site may adjust service offerings based on operational needs (including adding or removing models, changing group and quota policies, and suspending or terminating part or all of the service). This site is not liable for service changes caused by upstream provider adjustments or force majeure.'
    ),
    t(
      'The service is provided on an "as is" basis. This site does not guarantee the availability, accuracy, or continuity of upstream services, and may record necessary request data for billing and security audits.'
    ),
    t(
      'The final right to interpret this statement belongs to this site. This site may revise the statement based on operational needs or changes in laws and regulations; revisions take effect upon publication on this site, and continued use of the service constitutes acceptance of the revisions.'
    ),
  ]

  let statementBody: ReactNode
  if (isLoading) {
    statementBody = (
      <div className='space-y-3 py-2'>
        <Skeleton className='h-4 w-full' />
        <Skeleton className='h-4 w-[90%]' />
        <Skeleton className='h-4 w-[80%]' />
      </div>
    )
  } else if (isExternalLink) {
    statementBody = (
      <div className='space-y-3 py-2 text-sm'>
        <p className='text-muted-foreground'>
          {t(
            'The administrator configured an external link for this document.'
          )}
        </p>
        <a
          href={rawContent}
          target='_blank'
          rel='noopener noreferrer'
          className='text-primary hover:underline'
        >
          {t('View document')}
        </a>
      </div>
    )
  } else if (hasConfiguredContent) {
    statementBody = (
      <div className='py-2'>
        {contentIsHtml ? (
          <RichContent
            mode='html'
            htmlVariant='isolated'
            content={rawContent}
          />
        ) : (
          <RichContent
            mode='markdown'
            content={rawContent}
            className='prose-neutral dark:prose-invert max-w-none'
          />
        )}
      </div>
    )
  } else {
    statementBody = (
      <ol className='border-border/70 bg-muted/30 text-foreground list-decimal space-y-2 rounded-lg border px-4 py-3 pl-8 text-sm leading-6 sm:px-5 sm:py-4 sm:pl-9'>
        {defaultStatementItems.map((item) => (
          <li key={item}>{item}</li>
        ))}
      </ol>
    )
  }

  return (
    <AlertDialog open={props.open} onOpenChange={props.onOpenChange}>
      <AlertDialogContent className='flex max-h-[min(88dvh,760px)] w-[calc(100vw-1.5rem)] max-w-[42rem]! flex-col gap-0 sm:w-[min(42rem,calc(100vw-3rem))]'>
        <AlertDialogHeader className='shrink-0 px-4 pt-4 pb-3 text-left sm:px-5 sm:pt-5'>
          <AlertDialogTitle>{t('Usage Statement')}</AlertDialogTitle>
          <AlertDialogDescription
            render={<div />}
            className='mt-1 text-left leading-5'
          >
            {t(
              'Please read and agree to the usage statement before signing in.'
            )}
          </AlertDialogDescription>
        </AlertDialogHeader>

        <div className='min-h-0 flex-1 overflow-y-auto px-4 pb-1 sm:px-5'>
          {statementBody}
        </div>

        <AlertDialogFooter className='mx-0 mb-0 shrink-0 rounded-b-xl border-t p-3 sm:px-5'>
          <AlertDialogCancel>{t('Disagree')}</AlertDialogCancel>
          <Button onClick={props.onAgree}>{t('Agree and sign in')}</Button>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
